web:
  image: 6c8c6fc9ec40
  command: ./rzp-interview
  links:
    - db
  ports:
    - "8080:8080"
  environment:
    MYSQL_HOST: docker_db_1
    MYSQL_PORT: 3306
    MYSQL_USER: dev
    MYSQL_PASS: 123456
db:
  image: mysql/mysql-server:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: razorpay